### ISSUE TITLE
The performance and the sentiment label?

### ISSUE THREAD

**Issue by liutianling** [nadakamel/neural-networks-project#1]
It's a good work!
I want to know the performance of the model ?
And how the labels(1,2,3,0) denote to the sentiment label(pos, neg, ...)
Thanks.

**Comment by nadakamel** [comment]
@liutianling Thank you! :) 
- 0 denotes for subjective positive tweets
- 1 denotes for subjective negative tweets
- 2 denotes for subjective mixed tweets
- 3 denotes for objective tweets

**Comment by liutianling** [comment]
Thanks so much for your reply!
I will have a try in machine learning.
I wonder where can i get more training data of tweets? Thanks.

**Comment by nadakamel** [comment]
@liutianling Kaggle, Google Dataset Search, Github, etc.
